### ISSUE TITLE
Uploading only one file from talks

### ISSUE THREAD

**Issue by DDCreationStudios** [FCCVienna/FCCVienna#11]
I would suggest that people who give talks or presentations only upload one file. For example only a pdf or a opd file. In my opinion it is not necessary to upload more and different files, since it provides no additional value and blurs the folder. 
Before the talk it is possible to upload more versions as fallbacks but after the meetup they should be deleted to privode the best possible experience for people who join later on.

**Comment by 42pre** [comment]
I like your proposal. The part about being allowed to push 2 versions (eg PDF and ODP) before one's talk gives you enough flexibility (as I did this week).

If your proposal would be accepted, I would then argue that one general format for long term archival might be best. If created correctly, PDF is nice in that regard. Also for my prior talks I would then suggest keeping the PDFs and removing the ODPs.

Something like that could go into a "code of conduct" document for the FCCVienna repository?

Also would it be nice to encourage all speakers to put there talks in the talks section of the repository, even if they were web-presentations? Should the talks section be like a "nice if you put your presentation in there, but it's not really required" thing or not?

Would love to hear your opinions on that.

**Comment by DDCreationStudios** [comment]
TODO: 

Set up a upload standard and integrate it in our contribution file
