### ISSUE TITLE
Add a code of conduct

### ISSUE THREAD

**Issue by 42pre** [FCCVienna/FCCVienna#13]
Add a "code of conduct" either in the main [README.md](https://github.com/FCCVienna/FCCVienna/blob/master/Readme.md) or as a separate document (depending on the size).

Inspiration: http://todogroup.org/opencodeofconduct/

**Comment by robeerob** [comment]
Great idea. I am all for it. What do you say, @lukastillmann and @lukastillmann?

**Comment by DDCreationStudios** [comment]
Great idea @42pre! And thank you for the links. :) I will work on something as soon as possible! 🚀

**Comment by lukastillmann** [comment]
Yes, I agree. It's a good idea :)

**Comment by DDCreationStudios** [comment]
Notes from the meeting:
- Respect the house rules of the event locations

**Comment by DDCreationStudios** [comment]
close with pull request #25
