### ISSUE TITLE
Add a CONTRIBUTING file to the FCCVienna repository

### ISSUE THREAD

**Issue by 42pre** [FCCVienna/FCCVienna#14]
Inspiration: https://help.github.com/articles/setting-guidelines-for-repository-contributors/
> To help your project contributors do good work, you can add a file with contribution guidelines to the root of your project's repository. Then, whenever someone opens a pull request or creates an issue, they will see a link to that file.

Also the optional [repository Wiki](https://github.com/FCCVienna/FCCVienna/wiki) might be useful there for "further readings" and more detailed/complicated stuff.

**Comment by 42pre** [comment]
Also the optional [repository Wiki](https://github.com/FCCVienna/FCCVienna/wiki) might be useful there for "further readings" and more detailed/complicated stuff.

**Comment by 42pre** [comment]
More inspiration: https://github.com/git-lfs/git-lfs/blob/master/CONTRIBUTING.md

**Comment by robeerob** [comment]
Great idea, thanks! What do you guys think, @lukastillmann @DDCreationStudios?

**Comment by DDCreationStudios** [comment]
Great idea @42pre! And thank you for the links. :) I will work on something as soon as possible! 🚀

**Comment by lukastillmann** [comment]
Year, it's a great idea. But we'll have to think of some contributor guidelines first :) We do not have that many contributors at the moment, and we do not have that much content here either. So I'm not sure, wether we actually need this at the moment.

**Comment by 42pre** [comment]
My suggestion: start small and grow. I therefor created a minimal CONTRIBUTING file and started pull request. 

Even though we haven't got many contributors yet, we should still lay some ground rules, as that is actually easier done when there aren't that many people involved.

Also I don't see having contributing guidelines as a negative constraint, but rather something that helps newcomers to get positive results quickly and limit the negative feedback they receive on their pull requests due to lack of experience :wink:.

CheersM :100:

**Comment by 42pre** [comment]
Misclicked on that damn "Close and comment" button. :stuck_out_tongue_winking_eye:

**Comment by DDCreationStudios** [comment]
see #26
