### ISSUE TITLE
Use the GitHub kanban board to organize open issues

### ISSUE THREAD

**Issue by 42pre** [FCCVienna/FCCVienna#15]
GitHub provides a kanban board (hidden in the tab [Projects](https://github.com/FCCVienna/FCCVienna/projects)).

It would be nice, to fully utilize that feature to organize our issues.

Top of my head projects:
* "website" project (as proposed in issue #4)
* "how to contributing (talks etc.)" (issue #11, discussion on pull request #9)

I have dabbled with the feature in [my Sandbox](https://github.com/42pre/Sandbox/projects/1) and I really liked it. It's simple, but has enough features to be useful.

**Comment by 42pre** [comment]
I have dabbled with the feature on my [Sandbox](https://github.com/42pre/Sandbox/projects/1) and I really liked it. It's simple, but has enough features to be useful.

**Comment by DDCreationStudios** [comment]
I was already thinking about that! Thanks for pointing out Martin!

**Comment by robeerob** [comment]
Awesome feature. I echo @DDCreationStudios's thanks!
