### ISSUE TITLE
Use relative image references in markdown files

### ISSUE THREAD

**Issue by 42pre** [FCCVienna/FCCVienna#18]
Two options for images in the same folder as the Readme.md it is referenced in:

1. Using HTML syntax
   * Absolute: `<img src="https://github.com/FCCVienna/FCCVienna/blob/master/graphics/Logo1_white.png?raw=true" alt="" />`
   * Relative: `<img src="Logo1_white.png?raw=true" alt="" />`
2. Using markdown syntax
   * Absolute: `![](https://github.com/FCCVienna/FCCVienna/blob/master/graphics/Logo1_white.png?raw=true)`
   * Relative: `![](Logo1_white.png?raw=true)`

Personally I would prefer relative markdown references.

**Comment by robeerob** [comment]
LTGM :+1:
