### ISSUE TITLE
Mob programming sessions gone?

### ISSUE THREAD

**Issue by robeerob** [FCCVienna/FCCVienna#31]
I should probably have discovered this sooner, but where did our mob programming section go?

We used to have a folder where we kept all the code from our mob programming sessions, as well as a list for people to contribute with ideas for new sessions.

@DDCreationStudios

**Comment by robeerob** [comment]
Found it! It has it's own repository:
[https://github.com/FCCVienna/mobprogramming](https://github.com/FCCVienna/mobprogramming)

Maybe we should merge these two? What do you think?

**Comment by DDCreationStudios** [comment]
@robeerob 
I'd like to keep the repos separate like most Github organisations do. 
This repo is for pure information about the meetup and providing material for it. 
The other repo(s) should be having their own spirit -> e.g. programming sessions, small projects, ideas, etc
This structure also follows the idea of a modular architecture to keep everything as managable as possible :)

**Comment by robeerob** [comment]
👍
