### ISSUE TITLE
Plan the November Meetup

### ISSUE THREAD

**Issue by DDCreationStudios** [FCCVienna/FCCVienna#36]
- [X] At https://www.netconomy.net/
- [X] Mid November - 10th Nov 19:00?
- [X] Location: Walcherstrasse 11A, 1020 Wien
- [X] Food and drinks will be provided
- [x] Set up registration with limit
- [x] Check location
- [x] Talk: Browser Animation Performance, by Svetlozar Kalchev

**Comment by robeerob** [comment]
We didn't set a date yet? How about the 24th? @DDCreationStudios

**Comment by DDCreationStudios** [comment]
@robeerob Because I wanted to have my term at university scheduled.  I will send a mail to Netconomy and ask if the date works for them.

**Comment by robeerob** [comment]
@DDCreationStudios Updated the November overview with checkboxes for talks. @SvetlozarKalchev has committed to having a talk at this meetup.

**Comment by DDCreationStudios** [comment]
@robeerob  lets wait till I have visited the location. i am not quite sure if it makes sense to have talks when we have separated rooms ;)

**Comment by robeerob** [comment]
@DDCreationStudios Good point. It would be a pity if we don't have anything for Vitor and co to record, though. Could you perhaps check with Teresa the capacity of their biggest room? If it's big enough then we know whether or not to plan for talks.

**Comment by DDCreationStudios** [comment]
@robeerob I think it depends on the actual attendees. But we can separate the crowd into 3 groups and each group discusses various things in each room. For example one room focuses on talking about CSS, another about FreeCodeCamp and the third about React. 

The best way for planning would be to keep it as flexible as possible. I would suggest to have an generealized introduction and newsflash and then split into groups and at the end open up for get together. 

What do you think?

**Comment by robeerob** [comment]
@DDCreationStudios I love your idea about 3 groups and extended workshops. As mentioned above though, and via chat today, I propose to have at least 1 talk. After the talk we can do the 3 groups format.

We are blessed to have Vitor and Pusher Sessions wanting to film us for free over the coming months, so I think we should embrace that.

**Comment by DDCreationStudios** [comment]
Was successful!
