### ISSUE TITLE
Plan the October Meetup

### ISSUE THREAD

**Issue by DDCreationStudios** [FCCVienna/FCCVienna#37]
- [x] Location - [metalab](https://metalab.at/wiki/Lage)
- [X] Sponsor - Sipwise
- [X] Talks - Juho Vepsäläinen, matthias liszt
- [X] Ideas - freeCode/Explaining Gitflow/Showcase 
- [X] Date - 20th of October 
- [X] Filming 
- [X] Communicate on all platforms
- [x] Add Newsflash
- [X] invoicing

**Comment by DDCreationStudios** [comment]
Maybe a collaboration with Juho Vepsäläinen

**Comment by DDCreationStudios** [comment]
- for location contact metalab and stockwerk
- sponsor (no solution yet)
- ideas: besides talk a coding session

**Comment by MatthiasLiszt** [comment]
I would like to give a lightning talk about wallpaper tessellation. It should not be more than ten minutes, I already have a repo for it and I found a short one minute video on youtube.

**Comment by DDCreationStudios** [comment]
@MatthiasLiszt 
Hi Matthias! Thanks for the offer! Could you send my a link to the presentation? I have never heard about wallpaper tessellation. :) Is it possible to arrange the topic more as a showcase session oder discussion? Since we already have a talk we would like to foster more exchange with the people that are attending. 

@robeerob  What are your thoughts on that? Or should we maybe introduce a program option "lightning talk" where people present stuff in max 10mins and have it at the end of the meetup?

**Comment by robeerob** [comment]
@DDCreationStudios I am ok with having it as a regular 10 minute talk (plus questions) even. We have no talks planned yet as far as I know, and the talk proposal sounds nice.

@MatthiasLiszt Can you make sure you make it beginner friendly, or at the very least a 2 minute intro directed at JavaScript beginners? Will you be sharing code - if so what programming language?

**Comment by MatthiasLiszt** [comment]
Well, I plan to show around 12 slides and show my wallpaper generator on code pen. I also show how to use the base64 and the CSS to use it as webpage background. So it should be quick , basic and beginner friendly. https://codepen.io/mahagugu/pen/wroVZK ... I plan to write the presentation today, together with my weekly blog entry.

**Comment by MatthiasLiszt** [comment]
The slides for the talk are now on my repo at https://github.com/MatthiasLiszt/wallpapertessellation (file wallpaper.odp) . I am going now to my usual working place at the library in Meidling.

**Comment by DDCreationStudios** [comment]
@MatthiasLiszt Looks great! Thanks! Feel free to open a PullRequest for you slides and a new repo for your app.

**Comment by DDCreationStudios** [comment]
@MatthiasLiszt We will be recorded by Pusher again and they need the screen to be recorded. Will you use a MacBook? Or do you have any other Software, that records the screen in high quality? 

And also: Are you ok with being filmed and published online?

**Comment by MatthiasLiszt** [comment]
Yeah, it's alright for me. (actually I liked to be filmed)
However I use a chromebook and I do not know if GalliumOS supports recordings. 
Seems the easiest solution is to borrow a MacBook.

**Comment by DDCreationStudios** [comment]
@robeerob Any ideas?

**Comment by robeerob** [comment]
@MatthiasLiszt I'll see if I can connect you with the film crew, and see what they say. Think that have some know-how on how to set it up on Linux. Could you please send me an email to rob AT rob DOT ee so I have your email address to forward?

**Comment by robeerob** [comment]
@MatthiasLiszt I have sent the film crew an email with you in cc, and they will help you getting set up with some software for screenrecording.

**Comment by DDCreationStudios** [comment]
@robeerob You can add your newsflash, check the last box and close this issue :)
