### ISSUE TITLE
Plan the December Meetup

### ISSUE THREAD

**Issue by DDCreationStudios** [FCCVienna/FCCVienna#38]
- [x] Location - [RIAT](https://riat.ac.at/)
- [ ] Sponsor -
- [x] Talks - 
  - [x] CSS Scope? 
  - [ ] ??
- [ ] Code idea?
- [ ] Ideas - Christmas Special? 🎄 🎅 
- [x] Date - 16.12
- [ ] Add newsflash

Note for January meetup:
  - [ ] Browser Animation Performance, by Svetlozar Kalchev?

**Comment by robeerob** [comment]
RIAT can host us (added link and location above).

**Comment by DDCreationStudios** [comment]
@robeerob  for the date: 8th or 15th of Dec? I would vote for 8th. I think it's a holiday :)

**Comment by robeerob** [comment]
@DDCreationStudios the 8th does not work for me, unfortunately :( Shall we go for the 15th? Will check with RIAT.

**Comment by robeerob** [comment]
@DDCreationStudios Looks like 15th will work for RIAT. That date is ok for you as well?

They have some cryptocurrency events/series of events that week with international visitors, so we talked about either one of the guests or Matthias having a beginner friendly talk about blockchain, or for instance Monero (a cryptocurrency). What do you think?

**Comment by DDCreationStudios** [comment]
@robeerob Thanks for managing! Yes works good 👍 I think this time we should again aim for a classical meetup (rather than another coding workshop). So yes, great idea! 👏  I would prefer a talk about blockchain, because I am personally interested in it :P. But otherwise feel free to decide, you know the community best :) 
Maybe we should also add a Christmas special program point? Or end the program with a christmas special?  I have many exams in December so I can't schedule a "christmas & drinks" like we had last year. :(

**Comment by robeerob** [comment]
@DDCreationStudios Good point about talk focused meetup, and we can definitely think of something xmas-ey to end with ;) :tada: 

Just checked with Svetlozar, and he is not in Vienna on the 15th. Do you have someone in mind that we can ask to have a talk, should one of us have a talk, or maybe we can announce a "call for talk proposals" in "Developers Vienna" FB group and such?

**Comment by robeerob** [comment]
@DDCreationStudios 15th does not seem to work for RIAT after all. They suggested 14th or 16th. 14th is not good for me, but I think 16th could work. How about you?

Or should we try another space for this month?

**Comment by DDCreationStudios** [comment]
@robeerob hmmm a pity :/. The 14th and 16th are both not really good for me.  Shall we ask Zi8 or Stockwerk? Or I think you also had another place in mind and have been in contact with them. Whats the status of that?

**Comment by robeerob** [comment]
@DDCreationStudios yeah, indeed :( Maybe we can take the opportunity to try out Zi8? If they can't host us, I am also fine with Stockwerk. My other place idea never replied, so ruling them out for now.

Do you have contact details for Zi8?

**Comment by DDCreationStudios** [comment]
RIAT confirmed, one talk proposal so far, date for 16.12 confirmed
