### ISSUE TITLE
Create an offical FCCVienna Homepage

### ISSUE THREAD

**Issue by DDCreationStudios** [FCCVienna/FCCVienna#4]

**Comment by robeerob** [comment]
Great initiative. What's your plans.. stack, hosting on github pages..?

I'd gladly help out.

**Comment by MatthiasLiszt** [comment]
Ooo . time passed and I think I missed a lot ... the page has already been uploaded

**Comment by DDCreationStudios** [comment]
@robeerob  My idea was two-folded: 
Short-term I was thinking about writing a quick landing page on github pages - created during a showcase in one of our meetups. I think that's possible.
Long-term it would be nice to establish a professional offical homepage. However, I'm not quite sure if it is necessary since most of the coordination happens on the other platforms. Maybe we should discuss this question up at our next organizers meeting? 
I'm open for suggestions and ideas :)

**Comment by lukastillmann** [comment]
I don't think an official homepage is necessary. I think the meetup page together with the github channel amd social media is a good representation of our group at the moment. But I would hold on to the fccvienna domain for now. Depending on what you are paying for that @robeerob 

If you want to get creative @DDCreationStudios I won't stop you :-) But I don't quite see the benefits for now.

**Comment by 42pre** [comment]
My thoughts on the domain name:

Personally I would really like the domain to fully embrace the geographic location :).

Those are still available:

* fcc.wien (e.g. 34,90€/year through World4You)
* fccvienna.at (e.g. 13,90€/year through World4You)

**Comment by DDCreationStudios** [comment]
I would like to build like a custom event wall. Displaying or fetching the information from meetup.com.
Practically it shows the information with our own formatting.

**Comment by DDCreationStudios** [comment]
https://fccvienna.github.io/
