### ISSUE TITLE
Include freecodecamp.com link in meetup descriptions

### ISSUE THREAD

**Issue by robeerob** [FCCVienna/FCCVienna#6]
I just noticed that we have no good way for new meetup members to quickly discover our main website and what it is about. Current links go to forum (where there is no good route back to freecodecamp.com) and FB group (where link is hidden in "about" sidebar).

I propose we include a link and one line description in all out meetup event descriptions from now on.

**Comment by DDCreationStudios** [comment]
@robeerob Do you think it's neccessary? As someone pointed out in the last meetup many people aren't really reading the description and I think we should keep it as short and simple as possible. I think most of the people already know the mainpage, since you are litteraly coding on their homepage. The current link to the information about local groups is sufficient enough in my opinion. Do you agree?

**Comment by robeerob** [comment]
Yes, a lot of people don't read description at all, true. But some do, and those are the ones we are catering to. In my experience, most people at the meetups find us via meetup.com, and about 50% of those have never checked out the main FCC website. I agree with your point that short and simple is good, but then I would rather focus on e.g. one link for FCC main website, and one link that lists all our web presences. For example link to Readme.md, or create a dedicated "How to connect"/"Resources"/"Links" etc page.

What do you think?

**Comment by lukastillmann** [comment]
I agree with @robeerob . I've noticed a couple of people coming to the meetups having no clue what freecodecamp actually is. Also, we still have a lot of fluctuation. I think we could do a better job of explaining what we are and what we are doing ahead of time, so people know what to expect. 

I also agree, that the description should be kept short and sweet. Links to main fcc and link to the readme on github should be there, imo. We could think about more FAQ kind of explanation in the future
